/ Start the server
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});

services:
  - name: my-web-service
    type: web
    buildCommand: npm install && npm start
    env:
      - key: PORT
        value: "8080" # Use the port your app listens on
